# Generated by Django 3.1.7 on 2021-03-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('opposition', models.CharField(max_length=30)),
                ('venue', models.CharField(choices=[('T', 'Abbeydale Top Pitch'), ('B', 'Abbeydale Bottom Pitch'), ('D', 'Dronfield Woodhouse'), ('A', 'Away')], max_length=1)),
                ('notes', models.CharField(blank=True, default='', max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtureapp.team')),
            ],
        ),
    ]
